#!/usr/bin/env node

/**
 * Install a Summon pack or guide handle into the project at the current working
 * directory. The pack itself stays in .summon so it remains portable across AI
 * hosts; host-specific copies/configuration are small adapters around that source.
 *
 * Two shapes are installable:
 *   - Rich packs (dave-ramsey, elon): a persona plus playbooks, from packs/<pack>.
 *   - Handles (every registered guide): a thin skill that routes /<slug> to the
 *     summon.guide MCP server, from packs/handles/<slug>. Generated by
 *     scripts/gen-summon-handles.mjs.
 */
import { cp, mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const packs = new Set(["dave-ramsey", "elon"]);
const packsRoot = resolve(import.meta.dirname, "..", "packs");
const handlesIndexPath = join(packsRoot, "handles", "index.json");
const MCP_URL = "https://summon.guide/api/mcp";

const HELP = `Summon a grounded AI guide into the current project.

Usage:
  summon install <summon|summon-guide> [--global | --target <project-path>]
  summon install <guide> [--target <project-path>]
  summon install --all [--include-building] [--target <project-path>]
  summon list

<guide> is a rich pack (dave-ramsey, elon) or any guide slug from "summon list"
(for example senra, paul-graham, zero-to-one, founders-podcast). A handle
installs as /<slug> in Claude Code and Codex and routes to summon.guide's MCP
server; a rich pack also carries the persona and playbooks locally.

Examples:
  npx --yes github:adamtpang/summon.guide summon install dave-ramsey
  npx --yes github:adamtpang/summon.guide summon install senra
  npx --yes github:adamtpang/summon.guide summon install --all --target ../my-app`;

function fail(message) {
  console.error(`summon: ${message}`);
  process.exitCode = 1;
}

function loadHandles() {
  if (!existsSync(handlesIndexPath)) return [];
  try {
    return JSON.parse(readFileSync(handlesIndexPath, "utf8")).handles ?? [];
  } catch {
    return [];
  }
}

async function writeJson(path, value) {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, `${JSON.stringify(value, null, 2)}\n`);
}

async function readManifest(target) {
  const manifestPath = join(target, ".summon", "manifest.json");
  if (!existsSync(manifestPath)) return {};
  try {
    return JSON.parse(await readFile(manifestPath, "utf8"));
  } catch {
    return {};
  }
}

async function configureMcp(target) {
  const mcpPath = join(target, ".mcp.json");
  let mcp = { mcpServers: {} };
  if (existsSync(mcpPath)) {
    try { mcp = JSON.parse(await readFile(mcpPath, "utf8")); } catch {
      throw new Error(`could not read existing ${mcpPath}; it was left untouched`);
    }
  }
  mcp.mcpServers ??= {};
  mcp.mcpServers["summon-guide"] = { type: "http", url: MCP_URL };
  await writeJson(mcpPath, mcp);

  // Codex stores project MCP entries in TOML rather than .mcp.json. Preserve
  // an existing config and only add this named, remote server once.
  const codexConfigPath = join(target, ".codex", "config.toml");
  const codexServerHeader = "[mcp_servers.summon-guide]";
  const codexServer = `${codexServerHeader}\nurl = \"${MCP_URL}\"\n`;
  const existingCodexConfig = existsSync(codexConfigPath)
    ? await readFile(codexConfigPath, "utf8")
    : "";
  if (!existingCodexConfig.includes(codexServerHeader)) {
    await mkdir(dirname(codexConfigPath), { recursive: true });
    await writeFile(codexConfigPath, `${existingCodexConfig.trimEnd()}${existingCodexConfig ? "\n\n" : ""}${codexServer}`);
  }
}

async function installPack(pack, target) {
  const source = join(packsRoot, pack);
  if (!existsSync(source)) throw new Error(`pack files are missing for ${pack}`);

  const destination = join(target, ".summon", pack);
  await mkdir(dirname(destination), { recursive: true });
  await cp(source, destination, { recursive: true, force: true });

  // Claude Code discovers project skills from .claude/skills. Copying the
  // portable pack makes it work without installing a marketplace plugin.
  // Codex uses the same project-local skill shape.
  for (const host of [".claude", ".codex"]) {
    await mkdir(join(target, host, "skills", pack), { recursive: true });
    await cp(join(source, "SKILL.md"), join(target, host, "skills", pack, "SKILL.md"), { force: true, recursive: false });
    await cp(join(source, "PERSONA.md"), join(target, host, "skills", pack, "PERSONA.md"), { force: true });
  }

  const manifest = await readManifest(target);
  await writeJson(join(target, ".summon", "manifest.json"), {
    ...manifest,
    pack,
    installedAt: new Date().toISOString(),
    persona: `.summon/${pack}/PERSONA.md`,
    skill: `.summon/${pack}/SKILL.md`,
    packs: Array.from(new Set([...(manifest.packs ?? []), pack])).sort(),
    mcp: MCP_URL,
  });

  console.log(`Summoned ${pack} into ${target}`);
  console.log(`  Persona: .summon/${pack}/PERSONA.md`);
  console.log(`  Skills:  .claude/skills/${pack} and .codex/skills/${pack}`);
}

async function installHandle(handle, target) {
  const source = join(packsRoot, "handles", handle.slug, "SKILL.md");
  if (!existsSync(source)) throw new Error(`handle files are missing for ${handle.slug}; run npm run handles:generate`);

  const destination = join(target, ".summon", "handles", handle.slug);
  await mkdir(destination, { recursive: true });
  await cp(source, join(destination, "SKILL.md"), { force: true });
  for (const host of [".claude", ".codex"]) {
    await mkdir(join(target, host, "skills", handle.slug), { recursive: true });
    await cp(source, join(target, host, "skills", handle.slug, "SKILL.md"), { force: true });
  }
}

async function recordHandles(target, slugs) {
  const manifest = await readManifest(target);
  await writeJson(join(target, ".summon", "manifest.json"), {
    ...manifest,
    installedAt: new Date().toISOString(),
    handles: Array.from(new Set([...(manifest.handles ?? []), ...slugs])).sort(),
    mcp: MCP_URL,
  });
}

async function install(name, target, options) {
  if (name === "summon-guide") {
    const source = join(packsRoot, "summon-guide");
    for (const host of [".claude", ".agents", ".codex"]) {
      const destination = join(target, host, "skills", "summon-guide");
      const previous = join(destination, "SKILL.md");
      if (existsSync(previous) && !(await readFile(previous, "utf8")).includes("name: summon-guide")) throw new Error(`Unrelated skill at ${previous}; left untouched`);
      await mkdir(destination, { recursive: true });
      await cp(source, destination, { recursive: true, force: true });
    }
    console.log(`Installed summon-guide for Claude Code and Codex in ${target}. No Summon login, API key, or MCP setup required. Open a fresh chat and ask it to use summon-guide.`);
    return;
  }
  if (name === "summon") {
    const source = join(packsRoot, "summon");
    if (!existsSync(join(source, "registry.json"))) throw new Error("Universal skill missing; run npm run summon:generate");
    for (const host of [".claude", ".agents", ".codex"]) {
      const destination = join(target, host, "skills", "summon");
      const previous = join(destination, "SKILL.md");
      if (existsSync(previous)) {
        const content = await readFile(previous, "utf8");
        if (!content.includes("# Summon a guide")) {
          if (!content.includes("Summon control plane")) throw new Error(`Existing unrelated summon skill at ${previous}; left untouched`);
          const company = join(target, host, "skills", "summon-company");
          if (existsSync(company)) throw new Error(`Preserve existing ${company} before migrating the old summon skill`);
          await cp(destination, company, { recursive: true });
          await writeFile(join(company, "SKILL.md"), `---\nname: summon-company\ndescription: Manage the Summon company control plane, company onboarding, organization, and task routing.\n---\n\n${content.replaceAll('/summon', '/summon-company')}`);
        }
      }
      await mkdir(destination, { recursive: true });
      await cp(source, destination, { recursive: true, force: true });
    }
    console.log(`Installed /summon <guide name> for Claude Code and $summon <guide name> for Codex in ${target}.`);
    console.log("Default: carry context to production. Local guide material is available only when explicitly requested. Restart or open a fresh chat to discover the skill.");
    return;
  }
  const handles = loadHandles();
  const byslug = new Map(handles.map((h) => [h.slug, h]));

  if (options.all) {
    const chosen = handles.filter((h) => options.includeBuilding || h.availability === "ready");
    const installedHandles = [];
    let installedPacks = 0;
    for (const handle of chosen) {
      // A guide that ships as a rich pack gets the pack, not the thin pointer.
      if (packs.has(handle.slug)) { await installPack(handle.slug, target); installedPacks += 1; continue; }
      await installHandle(handle, target);
      installedHandles.push(handle.slug);
    }
    await recordHandles(target, installedHandles);
    await configureMcp(target);
    const skipped = handles.length - chosen.length;
    console.log(`Summoned ${installedHandles.length} guide handles${installedPacks ? ` and ${installedPacks} full pack${installedPacks === 1 ? "" : "s"}` : ""} into ${target}`);
    if (skipped) console.log(`  Skipped ${skipped} still-building guide${skipped === 1 ? "" : "s"} (add --include-building to install them too)`);
    console.log("  Skills:  .claude/skills/<slug> and .codex/skills/<slug>, one per guide");
    console.log("  MCP:     .mcp.json and .codex/config.toml -> summon.guide");
    console.log("Restart your AI client or reload the project to discover the new skills.");
    return;
  }

  if (packs.has(name)) {
    await installPack(name, target);
    await configureMcp(target);
    console.log("  MCP:     .mcp.json and .codex/config.toml -> summon.guide");
    console.log("Restart your AI client or reload the project to discover the new skill.");
    return;
  }

  const handle = byslug.get(name);
  if (!handle) {
    const near = handles.filter((h) => h.slug.includes(name) || h.name.toLowerCase().includes(name.toLowerCase())).slice(0, 5);
    throw new Error(`unknown guide "${name}".${near.length ? ` Did you mean: ${near.map((h) => h.slug).join(", ")}?` : ""} Run "summon list" to see every guide.`);
  }
  await installHandle(handle, target);
  await recordHandles(target, [handle.slug]);
  await configureMcp(target);
  console.log(`Summoned ${handle.name} into ${target} as /${handle.slug}`);
  if (handle.availability !== "ready") console.log(`  Note: ${handle.name} is still being onboarded; the handle reports status until the guide is live.`);
  console.log(`  Skill:   .claude/skills/${handle.slug} and .codex/skills/${handle.slug}`);
  console.log("  MCP:     .mcp.json and .codex/config.toml -> summon.guide");
  console.log("Restart your AI client or reload the project to discover the new skill.");
}

function list() {
  const handles = loadHandles();
  if (!handles.length) { console.log("No handles generated yet. Run: npm run handles:generate"); return; }
  const kinds = ["person", "channel", "book"];
  for (const kind of kinds) {
    const rows = handles.filter((h) => h.kind === kind);
    if (!rows.length) continue;
    console.log(`\n${kind} (${rows.length})`);
    for (const h of rows) {
      const flag = packs.has(h.slug) ? "  full pack" : h.availability !== "ready" ? "  building" : "";
      console.log(`  /${h.slug.padEnd(44)} ${h.name}${flag}`);
    }
  }
  console.log(`\n${handles.length} guides. Install one with "summon install <slug>" or all with "summon install --all".`);
}

const [, , command, ...args] = process.argv;
if (command === "list") {
  list();
} else if (command === "install" && args.length) {
  const all = args.includes("--all");
  const includeBuilding = args.includes("--include-building");
  const targetFlag = args.indexOf("--target");
  const global = args.includes("--global");
  const target = global ? (process.env.USERPROFILE || process.env.HOME) : targetFlag === -1 ? process.cwd() : args[targetFlag + 1];
  const name = args.find((a) => !a.startsWith("--") && a !== target);
  if (global && (targetFlag !== -1 || !["summon", "summon-guide"].includes(name) || all)) fail("--global is supported only for install summon or summon-guide, without --target or --all");
  else if (!target) fail("--target needs a project path");
  else if (!all && !name) { console.log(HELP); process.exitCode = 1; }
  else install(name, resolve(target), { all, includeBuilding }).catch((error) => fail(error instanceof Error ? error.message : String(error)));
} else {
  console.log(HELP);
  if (command) process.exitCode = 1;
}
